<div class="home-sub-container">
    <div class="home-sub-row">
	<div class="home-sub-col-main">
	    <div class="home-newsletter">
		<?php echo $this->getChildHtml('newsletter'); ?>
	    </div>
	</div>
    </div>
    <div class="home-sub-row">
	<div class="home-sub-col-main">
	    <div class="box-home-container home-produtos-destaque">
		<div class="socourus-home-title socourus-home-destaque-title">
		    <h2 class="socourus-h2">Destaque</h2>
		    <div class="socourus-custom-border">&nbsp;</div>
		</div>
		<div class="box-home-conteudo box-produtos-destaque">
		    <?php echo $this->getChildHtml('produtos_destaque'); ?>
		</div>
	    </div>
	</div>
    </div>
    <div class="home-sub-row">
	<div class="home-sub-col-main">
	    <div class="box-home-container home-produtos-esportistas">
		<div class="socourus-home-title socourus-home-esportistas-title">
		    <h2 class="socourus-h2">Esportistas</h2>
		    <div class="socourus-custom-border">&nbsp;</div>
		</div>
		<div class="box-home-conteudo box-produtos-esportistas">
		    <?php echo $this->getChildHtml('produtos_esportistas'); ?>
		</div>
	    </div>
	    <div class="box-home-banner-container">
		<div class="home-banner-lateral">
		    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner_lateral_cima')->toHtml(); ?>
		</div>
		<div class="home-banner-lateral">
		    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner_lateral_baixo')->toHtml(); ?>
		</div>
	    </div>
	</div>
    </div>
    <div class="home-sub-row sacLoja">
	<div class="home-sub-col-main">
	    <div class="box-home-container box-home-extras">
		<div class="box-home-extra box-sac">
		    <span class="sac-titulo">SAC - Loja Virtual</span>
		    <span class="sac-telefone">11 3813-5689</span>
		    <span class="sac-info">
			Atendimento de segunda &agrave; sexta-feira, das 8:30 &agrave;s 17:30
		    </span>
		</div>
		<div class="box-home-extra box-atendimento-online">
		    <img src="<?php echo $this->getSkinUrl('images/img_atendimento_online.png');?>" />
		</div>
		<div class="box-home-extra box-pesquisa-catalogo">
		    <?php echo $this->getChildHtml('catalog.search'); ?>
		</div>
	    </div>
	</div>
    </div>
    <script type="text/javascript">
	decorateGeneric($$('.box-home-banner-container .home-banner-lateral'), ['first', 'last']);
	decorateGeneric($$('.box-home-extras .box-home-extra'), ['first', 'last']);
    </script>
</div>