<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col width="1"  />
        <col/>
        <col width="2" />
		<col width="1" />
        <col width="1" />
        <thead>
            <tr>
				<th style="width: 1%;" rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Product') ?></th>
                <th style="width: 30%;" rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Descrição') ?></th>
                <th style="width: 10%;" colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Preço') ?></th>
                <th style="width: 10%;" rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Quatidade') ?></th>
                <th style="width: 10%;" colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
		<?php endforeach ?>
		<?php echo $this->getChildHtml('review_totals'); ?>
		</tbody>
    </table>
</div>