<?php
/**
 * Create account form template
 *
 * @see Esmart_Customer_Block_Form_Renderer_Image
 */
/* @var $this Esmart_Customer_Block_Form_Renderer_Image */
?>
<label for="<?php echo $this->getHtmlId()?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <input type="file" id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName()?>" value="" class="input-file" />
    <input type="hidden" id="<?php echo $this->getHtmlId()?>_value" value="<?php echo $this->getEscapedValue()?>" <?php if ($this->isRequired()): ?>class="required-entry" <?php endif;?>/>
    <?php if ($_message = $this->getAdditionalDescription()) : ?>
    <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>    
    <script type="text/javascript">
//<![CDATA[
    new Varien.FileElement('<?php echo $this->getHtmlId()?>');
//]]>
    </script>
</div>
