<?php
/**
 * Create account form template
 *
 * @see Esmart_Customer_Block_Form_Renderer_Textarea
 */
/* @var $this Esmart_Customer_Block_Form_Renderer_Textarea */
?>
<label for="<?php echo $this->getHtmlId()?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <textarea id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName()?>" rows="5" cols="25" class="input-text<?php echo $this->getHtmlClass(); ?>"><?php echo $this->getEscapedValue() ?></textarea>
    <?php if ($_message = $this->getAdditionalDescription()) : ?>
    <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>    
</div>
