<?php
/**
 * Madia Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Madia
 * @package	Madia_Adyen
 * @copyright	Copyright (c) 2011 Madia (http://www.madia.nl)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Madia_Adyen
 * @author     Omar,Muhsin <info@madia.nl>
 * @property   Madia B.V
 * @copyright  Copyright (c) 2011 Madia BV (http://www.madia.nl)
 */
?>
<?php if ($_info = $this->getInfo()): ?>
<?php $elv = unserialize($this->getInfo()->getPoNumber())?>
<?php echo Mage::helper('adyen')->__('Account holder: %s', $this->htmlEscape($elv['account_owner'])) ?><br/>
<?php echo Mage::helper('adyen')->__('Bank name: %s', $this->htmlEscape($elv['bank_name'])) ?><br/>
<?php echo Mage::helper('adyen')->__('Bank code: %s', $this->htmlEscape($elv['bank_location'])) ?><br/>
<?php echo Mage::helper('adyen')->__('Account number: xxx%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
<?php endif; ?>