<?php
    $_product = $this->getProduct();
?>
<div class="socourus-product-social-network">
    <!-- Botão Facebook -->
    <div class="socourus-btn-facebook">
	<iframe
	src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode($this->helper('core/url')->getCurrentUrl()); ?>&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21"
	scrolling="no"
	frameborder="0"
	style="border:none; overflow:hidden; width:100px; height:21px;"
	allowTransparency="true"></iframe>
    </div>
    
    <!-- Botão Google+ -->
    <div class="socourus-btn-googleplusone">
	
	<div class="g-plusone" data-size="medium" data-annotation="none" data-href="<?=($this->helper('core/url')->getCurrentUrl())?>"></div>
	
	<!-- Place this tag after the last +1 button tag. -->
	<script type="text/javascript">
	  window.___gcfg = {lang: 'pt-BR'};
	
	  (function() {
	    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
	    po.src = 'https://apis.google.com/js/plusone.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
	  })();
	</script>
    </div>
    
    <!-- Botão Twitter -->
    <div class="socourus-btn-twitter">
	<a
	href="https://twitter.com/share"
	class="twitter-share-button"
	data-url="<?php echo urlencode($this->helper('core/url')->getCurrentUrl()); ?>"
	data-lang="pt" data-count="none">Tweetar</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
</div>