<?php

$customer = Mage::helper('customer')->getCustomer()->getData();

?>

<?php if ($customer['group_id'] == 4): ?>
    <script>
        jQuery(document).ready(function(){
            jQuery(".taxvat").addClass("mask-cnpj");
            jQuery(".taxvat").removeClass("mask-cpf");
        });
    </script>
    <div class="page-title">
        <h1><?php echo $this->__('Edit Account Information') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate-edit" enctype="multipart/form-data">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
                </li>
                <li>
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                    </div>
                </li>
                <li>
                    <label class="required" for="razao_social"><em>*</em>Razão Social</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getCustomer()->getRazaoSocial()) ?>" name="razao_social" id="razao_social" autocomplete="off">
                    </div>
                </li>
                <li>
                    <label class="required" for="nome_fantasia"><em>*</em>Nome Fantasia</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getCustomer()->getNomeFantasia()) ?>" name="nome_fantasia" id="nome_fantasia" autocomplete="off">
                    </div>
                </li>
                <li>
                    <label class="required" for="inscricao_estadual"><em>*</em>Inscrição Estadual</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getCustomer()->getInscricaoEstadual()) ?>" name="inscricao_estadual" id="inscricao_estadual" autocomplete="off">
                    </div>
                </li>
                <li>
                    <label class="required" for="isento"><em>*</em>Isento</label>
                    <div class="input-box">
                        <input type="checkbox" name="isento" title="<?php echo $this->__('Isento ?') ?>" value="1" id="isento"<?php if($this->getCustomer()->getIsento()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                </li>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <li class="fields li-fields-cpf">
                    <?php if ($_taxvat->isEnabled()): ?>
                    <div class="field"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></div>
                    <?php endif ?>
                </li>                
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="change_password"><?php echo $this->__('Change Password') ?></label>
                </li>
            </ul>
        </div>
        <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes):?>
            <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
        <?php endif;?>
        <div class="fieldset" style="display:none;">
            <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="current_password"><?php echo $this->__('Current Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text" name="current_password" id="current_password" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="password"><?php echo $this->__('New Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text validate-password" name="password" id="password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set form-buttons">
            <p class="back-link">
                <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                    <!-- <small>&laquo; </small> -->
                    <?php echo $this->__('Go back') ?>
                </a>
            </p>
            <button type="submit" class="button" onclick="loadSubmit(this.form);" title="<?php echo $this->__('Save') ?>"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </form>

<?php else: ?>

    <div class="page-title">
        <h1><?php echo $this->__('Edit Account Information') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate-edit" enctype="multipart/form-data">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled()): ?>
            <li class="fields">
                <div class="field"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></div>
                <div class="field"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></div>
                <div class="field">
                    <label for="rg" class="required"><em>*</em>RG</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry mask-rg" value="<?php echo $this->htmlEscape($customer['rg']) ?>" name="rg" id="rg">
                    </div>
                </div>
                <div class="field"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
            </li>
            <?php endif ?>
            <li class="control">
                <div class="input-box">
                    <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                </div>
                <label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
    <?php if ($userDefinedAttributes):?>
        <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
    <?php endif;?>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="current_password"><?php echo $this->__('Current Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text" name="current_password" id="current_password" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password"><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <p class="back-link">
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <!-- <small>&laquo; </small> -->
                <?php echo $this->__('Go back') ?>
            </a>
        </p>
        <button type="submit" class="button" onclick="loadSubmit(this.form);" title="<?php echo $this->__('Save') ?>"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </form>

<?php endif ?>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate-edit', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(4).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(4).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    
    function loadSubmit(form){
        if(dataForm.validator.validate()) {
            form.submit();
        }
    }
    
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
