<div class="box-product-ratings">
    <div class="ratings">
        <div class="rating-box">
            <div class="rating" style="width:<?php echo ($this->getRatingSummary() ? $this->getRatingSummary() : 0); ?>%"></div>
        </div>
        <?php if ($this->getReviewsCount()) { ?>
            <span class="amount">
                <a href="#" onclick="var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl() ?>'; return false;">
                    <?php echo $this->__('%d Review(s)', $this->getReviewsCount()); ?>
                </a></span>
        <?php } ?>
    </div>
    <?php if ($this->getDisplayIfEmpty()) { ?>
        <p class="no-rating">
            <a class="comment-forwarder">
                <?php echo $this->__('Be the first to review this product') ?>
            </a>
        </p>
    <?php } ?>
</div>