<li class="clearfix" style="margin-bottom: 15px; <?php if($this->isCustomerLoggedIn()) echo "display:none;"?>">
    <div class="input-box input-radio-pf">
        <input onclick="" type="radio" id="billing:group_id" name="billing[group_id]" value="5" />
        <label for="billing:group_id"><?php echo $this->__('Pessoa física') ?> </label>
    </div>
    <div class="input-box input-radio-pj">
	<input onclick="" type="radio" id="billing:group_id" name="billing[group_id]" value="4" />
        <label for="billing:group_id"><?php echo $this->__('Pessoa jurídica') ?> </label>
    </div>
</li>

<?php
$formErrors = $this->getParentBlock()->formErrors;
$formErrors = (!empty($formErrors['billing_errors'])) ? $formErrors['billing_errors'] : array();

$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');

    $billingFields['firstname'] = '
        <div class="input-box input-firstname'.((in_array('firstname', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:firstname" class="firstname">'.$this->__('Name').'<span class="required">*</span></label><br />
            <input class="required-entry input-text" type="text" name="billing[firstname]" id="billing:firstname" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getFirstname()).'" />
        </div>';

    $billingFields['lastname'] = '
        <div class="input-box input-lastname'.((in_array('lastname', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:lastname" class="lastname">'.$this->__('Sobrenome').' <span class="required">*</span></label><br />
            <input class="required-entry input-text" type="text" name="billing[lastname]" id="billing:lastname" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getLastname()).'" />
        </div>';
?>

<?php if(!$this->isCustomerLoggedIn()): ?>

    <?php $billingFields['email'] = '
        <div class="input-box input-email'.((in_array('email', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:email">'.$this->__('Email').' <span class="required">*</span></label><br />
            <input type="text" name="billing[email]" id="billing:email" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getEmail())).'" title="'.$this->__('Email') .'" class="validate-email required-entry input-text" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->isCustomerLoggedIn() || in_array('email_registered', $formErrors)): ?>

    <?php $billingFields['email'] = $billingFields['email'].'
        <div class="clearfix" id="onestepcheckout-email-error" '.((!in_array('email_registered', $formErrors)) ? 'style="display: none"' : '').'>
            <div id="onestepcheckout-email-error-message" class="onestepcheckout-error">'.
                ((in_array('email_registered', $formErrors)) ? $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.') : $this->__('Invalid email address.'))
            .'</div>
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_telephone']):?>

    <?php $billingFields['telephone'] = '
        <div class="input-box input-telephone'.((in_array('telephone', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:telephone">'.$this->__('Telephone').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[telephone]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getTelephone())).'" title="'.$this->__('Telephone').'" class="required-entry input-text mask-telephone" id="billing:telephone" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_address']):?>

    <?php if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_address_fields')):?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){
                    $addressFields .= '<div class="input-box input-address-short'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <label for="billing:street'.$_i.'">'.$this->__('Street Address '.$_i).'<span class="required">*</span></label><br />
                    <input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i))).'" class="required-entry input-text onestepcheckout-address-line" />
                    </div>';
            }
            $billingFields['street'] = $addressFields;
        ?>
    <?php else:?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){

                    $addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i))).'" class="'.(($_i == 1)? 'required-entry ' : '').'input-text onestepcheckout-address-line" />';
                    $addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '<br/>': '');
            }
            $billingFields['street'] = '
                <div class="input-box input-address'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <label for="billing:street1">'.$this->__('Address').'<span class="required">*</span></label><br />
                    '.$addressFields.'
                </div>';
        ?>
    <?php endif; ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_country_id']):?>

    <?php
        $billingFields['country_id'] = '
            <div class="input-box input-country'.((in_array('country', $formErrors)) ? ' input-error' : '').'" style="display:none;">
                <label for="billing:country_id">'.$this->__('Country').' <span class="required">*</span></label><br />
                    '.$this->getCountryHtmlSelect('billing').'
            </div>';
    ?>

<?php else: ?>

<?php $billingFields['country_id'] = '
    <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" />';
?>

<?php endif; ?>

<?php if(!$this->settings['exclude_region']): ?>
    <?php $billingFields['region_id'] = '
        <div class="input-box input-region'.((in_array('region', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:region">'.$this->__('State/Province').' <span class="required">*</span></label><br/>
            <select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="validate-select" style="display:none">
                <option value="">&nbsp;</option>
            </select>
            <script type="text/javascript">
                $("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegionId()).'");
            </script>
            <input type="text" id="billing:region" name="billing[region]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegion())).'"  title="'.$this->__('State/Province').'" class="required-entry input-text" style="display:none" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_city']):?>

    <?php $billingFields['city'] = '
        <div class="input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:city">'.$this->__('City').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[city]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCity())).'" title="'.$this->__('City').'" class="required-entry input-text" id="billing:city" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_zip']): ?>
    <?php $srcLoader = $this->getSkinUrl('images/ajax-loader-custom.gif'); ?>
    <?php $billingFields['postcode'] = '
        <div class="input-box input-postcode'.((in_array('postcode', $formErrors)) ? ' input-error' : '').'" >
            <label for="billing:postcode">'.$this->__('CEP').' <span class="required">*</span></label><br />
            <input type="text" title="'.$this->__('CEP').'" name="billing[postcode]" id="billing:postcode" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getPostcode())).'" class="validate-zip-international required-entry input-text mask-postcode" onchange="getEndereco(this,\'billing\');" />
	    <div class="link-postcode">
		<a href="http://www.buscacep.correios.com.br/" target="_blank">'.$this->__("Don\'t know your Postal Code?").'</a>
	    </div>
	    <img style="display:none" src="'.$srcLoader.'" class="img-loader-jquery-billing" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_company']): ?>

    <?php $billingFields['company'] = '
        <div class="input-box input-company'.((in_array('company', $formErrors)) ? ' input-error' : '').'" style="display:none;">
            <label for="billing:company">'.$this->__('Company').'</label><br/>
            <input type="text" name="billing[company]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCompany())).'" title="'.$this->__('Company').'" class="input-text" id="billing:company" />
        </div>';
    ?>

<?php endif; ?>

<?php if(!$this->settings['exclude_fax']): ?>

    <?php $billingFields['fax'] = '
        <div class="input-box input-fax'.((in_array('fax', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:fax">'.$this->__('Fax').'</label><br/>
            <input type="text" name="billing[fax]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getFax())).'" title="'.$this->__('Fax').'" class="input-text" id="billing:fax" />
        </div>';
    ?>

<?php endif; ?>

<?php
    $_taxvat = false;
    try {
        if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_pillwaxeuvat_support')){
            $_taxvat = $this->getLayout()->createBlock('euvat/widget_taxvat');
        }
    } catch (Exception $e) {
    }
    if(!is_object($_taxvat)){
        $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
    }
?>

<?php if(is_object($_taxvat) && $_taxvat->isEnabled()): ?>

    <?php $billingFields['taxvat'] =
            $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
    ?>

<?php endif; ?>

<?php
    try {
        $_dob = $this->getLayout()->createBlock('customer/widget_dob');
    } catch (Exception $e) {
        $_dob = false;
    }
?>

<?php
    try {
        $_gender = $this->getLayout()->createBlock('customer/widget_gender');
    } catch (Exception $e) {
        $_gender = false;
    }
?>

<?php if (is_object($_dob) && $_dob->isEnabled()): ?>

    <?php $billingFields['dob'] = '
        <div class="field retailer-dob">
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>

<?php endif; ?>

<?php if (is_object($_gender) && $_gender->isEnabled()): ?>

    <?php $billingFields['gender'] = '
        <div class="field retailer-gender">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>

<?php endif ?>

<?php if(!$this->isCustomerLoggedIn() && $helper->showCreateAccount()): ?>

    <?php $billingFields['create_account'] = '
        <div class="input-box">
            <input id="id_create_account" type="checkbox" name="create_account" value="1" '.((isset($_POST['create_account']) && $_POST['create_account'] == '1') ? ' checked="checked"' : '').' />
            <label for="id_create_account">'.$this->__('Create an account for later use').'</label>
        </div>

        <script>
        document.observe("dom:loaded", function() {
            $("id_create_account").observe("click", function(e) {
                var element = e.element();
                if(element.checked) {
                    $("onestepcheckout-li-password").show();
                }
                else    {
                    $("onestepcheckout-li-password").hide();
                }
            });
        });
        </script>';
    ?>

<?php endif; ?>

<?php if($helper->showPasswords() && !$this->isCustomerLoggedIn()): ?>

    <?php
        //id="onestepcheckout-li-password"
        $billingFields['password'] = '
        <li id="onestepcheckout-li-password" '.(($helper->hidePasswords()) ? 'style="display: none;"':'').'>
            <div class="input-box input-password'.((in_array('password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:customer_password">'.$this->__('Password').'</label><br/>
                <input type="password" class="input-text required-entry validate-password" value="'.((isset($_POST['billing']['customer_password'])) ? $_POST['billing']['customer_password'] : '').'" title="Password" id="billing:customer_password" name="billing[customer_password]"/>
            </div>
            <div class="input-box input-password input-real-password-field'.((in_array('confirm_password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:confirm_password">'.$this->__('Confirm the password').'</label><br/>
                <input type="password" class="input-text required-entry validate-cpassword" value="'.((isset($_POST['billing']['confirm_password'])) ? $_POST['billing']['confirm_password'] : '').'" id="billing:confirm_password" title="'.$this->__('Confirm the password').'" name="billing[confirm_password]"/>
            </div>
        </li>';
    ?>

<?php endif; ?>

<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>

    <?php $billingFields['save_in_address_book'] = '
        <li class="control">
            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="'.$this->__('Save in address book').'" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"'.(($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getSaveInAddressBook())) ? 'checked="checked"':'').' class="checkbox" /><label for="billing:save_in_address_book">'.$this->__('Save in address book').'</label>
        </li>';
    ?>

<?php else:?>

    <?php $billingFields['save_in_address_book'] = '
        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>';
    ?>

<?php endif; ?>

<?php
    $billingFields['user_data'] = '<div class="billing-data"?>
    <li class="clearfix">
	'.$billingFields["firstname"].'
	'.$billingFields["lastname"].'
    </li>
    <li class="clearfix">
	'.$billingFields["email"].'
    </li>
    <li class="clearfix">
	'.$billingFields["telephone"].'
    </li>
</div>';    
?>

<?php //$billingFields = $this->getBillingFieldsOrder($billingFields);?>

<?php /*foreach($billingFields as $key => $value):?>
    <?php if(!empty($value['has_li'])):?>
        <?php echo implode('',$value['fields']);?>
    <?php else:?>
        <li class="clearfix"><?php echo implode('',$value['fields']);?></li>
    <?php endif;?>
<?php endforeach;*/?>

<?php if(!$this->isCustomerLoggedIn()):?>
<div class="retailer">
    <p>
	<h3 id='dados_contato_atacado_titulo' style="display: none">Dados Atacado</h3>
    </p>
    <div class="billing-name clearfix">
	<?php echo $billingFields['firstname']; ?>
        <?php echo $billingFields['lastname']; ?>
    </div>
    <div class="billing-taxvat clearfix">
	<li class="clearfix li-input-cpf">
	    <div class="input-box input-cpf">
		<label class="taxvat-label" for="billing:taxvat">CPF<span class="required">*</span></label>
<input type="text" class="input-text required-entry billing-taxvat" title="" value="<?php echo $this->htmlEscape($this->getCustomer()->getTaxvat()) ?>" name="billing[taxvat]" id="billing:taxvat" />
		<!-- <input type="hidden" name="billing[taxvat]" id="billing:taxvat" /> -->
	    </div>
	</li>
	<li class="clearfix retailer-rg">
	    <div class="input-box">
		<label for="billing:rg">RG<span class="required">*</span></label><br />
		<input type="text" class="input-text input-rg required-entry mask-rg" value="<?php echo $this->htmlEscape($this->getCustomer()->getRg()) ?>" name="billing[rg]" id="billing:rg" />
	    </div>
	</li>
    </div>
    <li class="clearfix">
        <?php echo $billingFields['telephone']; ?>
	
        <?php echo $billingFields['email']; ?>
    </li>    
    
</div>

<div class="wholesale" style="display:none;">
    <li class="clearfix">
        <div class="input-box input-razao-social">
	    <label for="billing:razao_social">Razão Social<span class="required">*</span></label>
            <input type="text" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getCustomer()->getRazaoSocial()) ?>" name="billing[razao_social]" id="billing:razao_social" />
        </div>
    <!--</li>-->
    <!--<li class="clearfix">-->
        <div class="input-box input-nome-fantasia">
	    <label for="billing:nome_fantasia">Nome Fantasia<span class="required">*</span></label>
            <input type="text" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getCustomer()->getNomeFantasia()) ?>" name="billing[nome_fantasia]" id="billing:nome_fantasia" />
        </div>
    </li>
    <li class="clearfix">
        <div class="input-box input-inscricao-estadual">
	    <label for="billing:inscricao_estadual">Inscrição Estadual<span class="required">*</span></label>
            <input type="text" class="input-text required-entry" name="billing[inscricao_estadual]" id="billing:inscricao_estadual" />
        </div>
    <!--</li>-->
    <!--<li class="clearfix">-->
        <div class="input-box isento-wholesale">
            <input type="checkbox" name="billing[isento]" title="Isento" value="1" id="billing:isento" class="checkbox" />
	    <label for="billing:isento">Isento</label>
        </div>
    </li>
</div>
<?php endif; ?>

<div class="billing-address">
    <?php if($this->isCustomerLoggedIn()):?>
	<?php echo $billingFields['user_data']; ?>
    <?php endif; ?>
    <li class="clearfix" style="position: relative;">
        <?php echo $billingFields['postcode']; ?>
    <!--</li>-->
    <!--<li class="clearfix">-->
        <?php echo $billingFields['region_id']; ?>
    </li>
    <li class="clearfix">
        <?php echo $billingFields['city']; ?>
    </li>
    <li class="clearfix">
        <div class="input-box input-address">
            <label for="billing:street1">Endereço<span class="required">*</span></label><br>
            <input type="text" class="required-entry input-text onestepcheckout-address-line" value="<?php echo $this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet(1))) ?>" id="billing:street1" name="billing[street][]" title="Address">
        </div>
    </li>
    <li class="clearfix">
        <div class="input-box input-address input-address-number">
            <label for="billing:street2">Número<span class="required">*</span></label><br>
            <input type="text" class="required-entry input-text onestepcheckout-address-line" value="<?php echo $this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet(2))) ?>" id="billing:street2" name="billing[street][]" title="Número">
        </div>
        <div class="input-box input-address input-address-complement">
            <label for="billing:street3">Complemento</label><br>
            <input type="text" class="input-text onestepcheckout-address-line" value="<?php  echo $this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet(3))) ?>" id="billing:street3" name="billing[street][]" title="Complemento">
        </div>
    </li>
    <li class="clearfix">
        <div class="input-box input-address">
            <label for="billing:street4">Bairro<span class="required">*</span></label><br>
            <input type="text" class="required-entry input-text onestepcheckout-address-line" value="<?php  echo $this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet(4))) ?>" id="billing:street4" name="billing[street][]" title="Bairro">
        </div>
    </li>
    <?php
	$customer = Mage::helper('customer')->getCustomer()->getData();
	if($customer['group_id'] != 4):?>
	    <li class="clearfix">
		<?php echo $billingFields['dob']; ?>
	    <!--</li>-->
	    <!--<li class="clearfix">-->
		<?php echo $billingFields['gender']; ?>
	    </li>
    <?php endif; ?>
    <li class="clearfix">
        <?php echo $billingFields['country_id'];?>
    </li>
</div>

<div class="user-data">
    <?php echo $billingFields['create_account'] ?>
    <?php echo $billingFields['password'] ?>
    <?php echo $billingFields['save_in_address_book'] ?>
</div>

<script>
    jQuery('input[id="billing:postcode"]').live("blur",function() {
        <?php if($this->settings['enable_ajax_save_billing']): ?>
            get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>',
            <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, true)();
        <?php endif; ?>
    });
</script>


