<div class="box-cart-extras">
    <div class="box-cart-extra box-sac">
	<span class="sac-titulo">SAC - Loja Virtual</span>
	<span class="sac-telefone">11 3813-5689</span>
	<span class="sac-info">
	    Atendimento de segunda &agrave; sexta-feira, das 8:30 &agrave;s 17:30
	</span>
    </div>
    <div class="box-cart-extra box-atendimento-online">
	<img src="<?php echo $this->getSkinUrl('images/img_atendimento_online.png');?>" />
    </div>
    <div class="box-cart-extra box-pesquisa-catalogo">
	<?php echo $this->getChildHtml('catalog.search'); ?>
    </div>
</div>
<script type="text/javascript">
    decorateGeneric($$('.box-cart-extras .box-cart-extra'), ['first', 'last']);
</script>