<?php
    $_helper = $this->helper('catalog/output');
    
    if($this->getCategoryId()) {
	$layer = $this->getLayer();
	$category = Mage::getModel('catalog/category')->load($this->getCategoryId());
	$layer->setCurrentCategory($category);
	$_productCollection = $layer->getProductCollection();
    }
    
    if($_productCollection && $_productCollection->count()) { ?>
	<div class="lista-produtos-container">
	    <button id="produtos-destaque-next" class="next">&nbsp;</button>
	    <button id="produtos-destaque-prev" class="prev">&nbsp;</button>
	    <div id="produtos-destaque">
		<ul class="lista-produtos">
	    <?php foreach ($_productCollection as $_product){ ?>
		    <li class="item-lista-produto">
			<div class="produto">
			    <div class="produto-img">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			    </div>
			    <div class="produto-nome">
				<div class="produto-wrapper">
				    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				    <h2 class="product-name">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
					<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
					</a>
				    </h2>
				</div>
			    </div>
			    <div class="produto-precos">
				<div class="produto-wrapper">
				    <?php echo $this->getPriceHtml($_product, true) ?>
				</div>
			    </div>
			    <div class="produto-precos-prazo">
				<div class="produto-wrapper">
				    <? $parcela = ($_product->getMinimalPrice() / 6);?>
				    <span class="price"><span>6x de <?php echo $this->helper('core')->currency($parcela,true,false) ?></span> sem juros no cart&atilde;o de cr&eacute;dito</span>
				</div>
			    </div>
			</div>
		    </li>
	    <?php } ?>
		</ul>
	    </div>
	</div>
	<script type="text/javascript">
	    jQuery(document).ready(function(){
		jQuery("#produtos-destaque").jCarouselLite({
		    btnNext: "#produtos-destaque-next",
		    btnPrev: "#produtos-destaque-prev",
		    visible: 4,
		    start: 0
		});
		
		if(BrowserDetect.browser == 'Explorer' && BrowserDetect.version <= 8) {
		    jQuery("#produtos-destaque .lista-produtos .item-lista-produto").each(function(){
			jQuery(this).css('height', jQuery(this).find('.produto').css('height'));
			jQuery(this).css('width', jQuery(this).find('.produto').css('width'));
		    });
		}
	    });
	</script>
<? } ?>