<div class="form-search-container">
	<div class="form-search-container-sac">
	    <span class="sac-titulo">SAC - Loja Virtual</span>
	    <span class="sac-telefone">11 3813-5689</span>
	    <span class="sac-info">
		Atendimento de segunda &agrave; sexta-feira, das 8:30 &agrave;s 17:30
	    </span>
	</div>
	<div class="form-search-container-atendimento-online">
	    <img src="<?php echo $this->getSkinUrl('images/img_atendimento_online.png');?>" />
	</div>
	<div class="form-search-container-pesquisa-catalogo">
	    <?php echo $this->getChildHtml('catalog.search'); ?>
	</div>
</div>