<?php
/**
 * Madia Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Madia
 * @package	Madia_Adyen
 * @copyright	Copyright (c) 2011 Madia (http://www.madia.nl)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Madia_Adyen
 * @author     Omar,Muhsin <info@madia.nl>
 * @property   Madia B.V
 * @copyright  Copyright (c) 2011 Madia BV (http://www.madia.nl)
 */
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_owner"><?php echo $this->__('Account holder name') ?> <span class="required">*</span></label><br />
                <input type="text" title="<?php echo $this->__('Account holder name') ?>" class="validate-ipayment-elv-owner required-entry input-text" id="<?php echo $_code ?>_owner" name="payment[owner]" value="<?php echo $this->htmlEscape($this->getInfoData('echeck_account_name')) ?>" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label><br />
                <input 
                	type="text" id="<?php echo $_code ?>_account_number" name="payment[account_number]" 
                	title="<?php echo $this->__('Account Number') ?>" 
                	class="validate-ipayment-elv-account-number required-entry input-text" 
                	value="" autocomplete="off" 
                	onkeyup="javascript: limitText(this,10,false);" onkeydown="javascript: limitText(this,10,false);"
                />
            </div>
        </li>
         <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_location"><?php echo $this->__('Bank Location ID') ?> <span class="required">*</span></label><br />
                <input 
	                type="text" id="<?php echo $_code ?>_bank_location" name="payment[bank_location]" 
	                title="<?php echo $this->__('Bank Location') ?>" 
	                class="validate-ipayment-elv-account-number required-entry input-text" 
	                value="" autocomplete="off" 
	                onkeyup="javascript: limitText(this,8,false);" onkeydown="javascript: limitText(this,8,false);"
                />
            </div>
        </li>
               
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_code"><?php echo $this->__('Bank Location (City)') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_bank_code" name="payment[bank_code]" title="<?php echo $this->__('Bank Location (City)') ?>" class="validate-ipayment-elv-bank-code required-entry input-text" value="" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_name"><?php echo $this->__('Bank Name') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_bank_name" name="payment[bank_name]" title="<?php echo $this->__('Bank Name') ?>" class="validate-ipayment-elv-bank-name required-entry input-text" value="" />
            </div>
            <input type="hidden" name="payment[additional_data]" value="" />
            <input type="hidden" id="ipayment_elv_request_status" value="" />
        </li>
    </ul>
</fieldset>
<div>
<span id="ipayment-elv-please-wait" style="display:none;" class="opc-please-wait">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Submitting payment information...') ?> &nbsp;
</span>
</div>

